### ISSUE TITLE
how do we verify the data that we add into repository？

### ISSUE THREAD

**Issue by yilongx** [intel/NMPRK#31]
how do we verify the data that we add into repository?  such ad SEL, SDR and FRU. 
Cloud you give me the detail steps? Thanks a lot.

**Comment by jrmassoni** [comment]
I am working on the same issue and probably will not finish it on this release.  The SDR is the closest to working.

For the SDR ideally you would read the SDR from the server into a file.  Clear the SDR, then write the SDR file back out to the server.  Read the SDR back into a file and then compare the two files to make sure they are the identical.  I believe the version I have of the NMPRK supports this but I have not fully tested it.  I want to be careful because if you clear the SDR, your computer may not function correctly, therefore before you do this test you need the original SDR file and a way to restore it in case the NMPRK doesn’t work.  I am still working to test this.

Regarding the FRU.

The test application correctly reads the FRU data into a file, but I don’t believe the write FRU function works correctly for replacing the FRU data.  Therefore you can’t verify the writing of the FRU data until I fix this.  The problem is it tries to write the FRU data the same as it would write SDR data, but the FRU data is different.  This needs to be fixed before you can test writing the FRU data.

Regarding the SEL.

I removed the add SEL routine.  It makes no sense to write SEL data back to the SEL, because the SEL will modify the data, therefore you can only test reading the SEL data.   There is a function to add events to the SEL, which would be useful, unfortunately that function was never implemented in the NMPRK.  You can also test clearing the SEL.
