### ISSUE TITLE
it will give me an error when i call function setFruData() first time.

### ISSUE THREAD

**Issue by yilongx** [intel/NMPRK#32]
it will give me an error " stack smashing detected " when i call function setFruData() first time and will succeed in next time. the console info as follows:
###### ##########################################################################

Attempting to connect to device..... Passed
Attempting to run basic test command.... Passed
Sent 2 Bytes.  Expecting back 15 bytes got back 15..... Passed
Resp Bytes:
21 1 1 4 2 bf 57 1 0 49 0 1 7 50 b 
testing nmprk::ipmi::fru function:
Attempting to access FRU..... Passed
Fru is access by byte
Attempting to read first entry from FRU.....Passed

**\* stack smashing detected ***: ./testIpmi terminated
Segmentation fault
cloud@otc-cloud10:~/nmprk-RC3-3/nmprk/ipmi/test$ ^C
cloud@otc-cloud10:~/nmprk-RC3-3/nmprk/ipmi/test$ ./testIpmi 1
Attempting to connect to device..... Passed
... ... 
testing nmprk::ipmi::fru function:
Attempting to access FRU..... Passed
Fru is access by byte
Attempting to read first entry from FRU.....Passed
Attemping Set FRU date... Passed
... ... 
Attempting to disconnect the device..... Passed
Press the Enter key to exit

**Comment by jrmassoni** [comment]
It would appear that you do not have the structures correctly set up, which is why are getting the segmentation fault.  I am currently working with the setFruData command and it appears to work fine, although fails to actually write any data.  As soon as I get it working I will provide you an update.

**Comment by jrmassoni** [comment]
The FRU routines have been fixed in the release I am gving you on 9/20/12.  Please retest and see that they work.  You should first run the testIpmi routing and save the FRU file in case it is corrupted later.  Then uncomment the conditional code so you can try the program routine.  If successful it will write over the previous fru data. If you want to see the data change, then you will need to modify the FRU file, but beware, you can easily corrupt the FRU file and make it unusable (don't change the initial 10 bytes).  This is why you need to save the original, so you can go back and retore it if later.
