### ISSUE TITLE
setPolicy failed after only do lib and device initial

### ISSUE THREAD

**Issue by yilongx** [intel/NMPRK#6]
setPolicy failed after only do lib and device initial. 

error message as follow：
###### 

Library initalized!
Device initalized!
Device Capabilities:
... ...
Failed!
Caught Exception setPolicy(0x01): Code[209] MSG[Invalid Domain Specified]
## detail test code as follows:
# include <iostream>
# include <nmprk_ipmi.h>
# include <nmprk_exception.h>
# include <nmprk_defines.h>
# include <nmprk_ipmi_global.h>
# include <nmprk_translation.h>
# include <nmprk_translation_defines.h>

int main(int argc, char\* argv[])
{
    nmprk::ipmi::device d;
    d.type = nmprk::ipmi::device_nm;
    d.address = "local";
    d.transport = 0x2c;
    d.bridge = 0x06;

```
bool result;
try {
    result = nmprk::translation::swSubSystemSetup(nmprk::translation::initLibrary,NULL);
}catch(nmprk::nmprkException* e) {
    std::cout << "Failed!\nCaught Exception swSubSystemSetup(library): Code[" << e->errorCode << "] MSG[" << e->errorMsg << "]\n";
    return -1;
}

if(!result) {
    std::cout << "Library init failed!\n";
    return -1;
}else 
    std::cout << "Library initalized!\n";

try {
    result = nmprk::translation::swSubSystemSetup(nmprk::translation::initDevice,&d);
}catch(nmprk::nmprkException* e) {
    std::cout << "Failed!\nCaught Exception swSubSystemSetup(device): Code[" << e->errorCode << "] MSG[" << e->errorMsg << "]\n";
    return -1;
}
if(!result) {
    std::cout << "Device init failed!\n";
    return -1;
}else 
    std::cout << "Device initalized!\n";

nmprk::translation::policy_t policy;
policy.policyId = 0x02;
policy.policyEnabled = true;
policy.policyType = nmprk::translation::policyPower; // power limit, not thermal limit
policy.component = nmprk::translation::domainSystem; // set a limit for the whole system
policy.sendAlert = true;         // send alert if policy.policyLimit is breached for longer then policy.correctionTime
policy.shutdown = false;         // shutdown system if policy.policyLimit is breached for longer then policy.correctionTime
policy.statReportingPeriod = 10; // how long values are averaged over
policy.correctionTime = 10;      // how long a policy can be over its limit
// before policy.sendAlert and policy.shutdown are performed if true
policy.policyLimit = (sample->avg - (sample->avg * .10));
try {
    result = nmprk::translation::setPolicy(&d, &policy);
}catch(nmprk::nmprkException* e) {
    std::cout << "Failed!\nCaught Exception setPolicy(0x01): Code[" << e->errorCode << "] MSG[" << e->errorMsg << "]\n";
    return -1;
}
if(!result) {
    std::cout << "Unable to set power cap!\n";
    return -1;
}else 
    std::cout << "Power cap set to " << policy.policyLimit << " Watts!\n";

try {
    nmprk::translation::swSubSystemSetup(nmprk::translation::unInitDevice,&d);
    nmprk::translation::swSubSystemSetup(nmprk::translation::unInitLibrary,NULL);
}catch(nmprk::nmprkException* e) {
    std::cout << "Failed!\nCaught Exception uninitalizing everything: Code[" << e->errorCode << "] MSG[" << e->errorMsg << "]\n";
    return -1;
}

return 0;
```

}

**Comment by jrmassoni** [comment]
Tried doing a setPolicy after the lib and dev init and it worked fine.  Believe the reason the above code failed is that the correction time is invalid.  This should have been reported back in the exception code. It was when I tried.  This is the reason you should run a getCapabilities first, so that you know you are within bounds.  This is not a bug and appears to be a case of the programmer not using getCapabilities to check the input values to setPolicy to see if they are valid.

**Comment by yilongx** [comment]
Although correction time is invalid, i think it should report  "correction time out of range " not  "Invalid Domain Specified"

**Comment by jrmassoni** [comment]
Unfortunately because this is a reference kit and not production code.  It is the responsibility of the calling program to verify all input data to a call and to ensure all functions are called in the correct order.  That is not to say we are not interested in improving the functionality and return codes of the NMPRK.  It appears in this case the calling program is at fault.  It is agreed that the NMPRK should improve its responses to calls that fail and we have resources to do so.

**Comment by yilongx** [comment]
This issue's essential is that we can't  set the same policy more than one time. we think it is unreasonable and it should give some Prompt or do nothing.

**Comment by jrmassoni** [comment]
In the testTranslation.exe program I setPolicy 3 and then call it again and change the policy from 350 watts to 330 watts.  Calling it a second time should be no issue as shown in that example, but you must first disable the policy in order to change it. This is the way Node Manager is implemented on the Server, the NMPRK has no control over that behavior. I hope this answers your question.
